apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:YBjNL+LP2Z/aw+CXK5yaPVkoan7Y5XxUpmHn1B1bN8hXG64XASugsFZKCkpPPEyymW+kUKasGFqemWlSCDkfhSTiOILwxzbeBnonnk1ojIK3,iv:JuchPIHpL8YADVQzo8LVcBC0mdMcHVlNdvaOPmGACIU=,tag:/7O2Qs7rU4Job4YCLvlfxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dsq075je2z0h7fe8hl72g08l368rwrlrx2zhryhkvs4qxszdtezqj5xltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSVFvWHhydnVSWXA1L3pk
            R1ZlMTBhS3RKTkFzZXBjZEFKdzlxVVRiTVNJClUzTUNBRUlJSVAyTjlnWWVvWnI0
            Um5YcFNya2pGb01QcmpVRE16NDFKeGcKLS0tIEdKbHRMNXZWSGRTODJxbmtRS1M1
            dVo0SllpNE5ZeFhFVGJlV2hwajdMVlEKvEQw5D08EjfT0EcJxG29CyzJMgs2j8s/
            L2DwhoaM0UiZowXD2lKl80ydW6w7VzYf4EFren5Hh7NrNsgpiRNwHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T12:25:51Z"
    mac: ENC[AES256_GCM,data:UvMcYCqY+8OnpwkwiItu1yWlq8BRIlH0BoK9u9P9mQo6sLKXpMuq8Z5CVwveaaP/nccnaBx2fhDRlPWL52B3l76V67TKO+mBee5v1v3P8c5BFBoJMb0t8nnihqT12pmlV13h2ExyDOARDXSOif+VXY6yw0ELjnF1ERN1rqBbiSE=,iv:8hOkCQrc0SRhK9OyQZLzJHLcei8hsy5FLEfy3XrJmKc=,tag:jTMHUeBcmzEPv1WnXeVakw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
